### ISSUE TITLE
Aucune données n'apparait

### ISSUE THREAD

**Issue by ericnrcoin** [Youpit44/cryptoscreener#1]
Bonjour,
Je viens d'essayer votre projet mais cela ne donne rien d'autre que l'entête 
![image](https://user-images.githubusercontent.com/36274908/39761191-bb657654-52d7-11e8-8804-15af20faf654.png)
J'ai pourtant bien copié le fichier Index.html et le répertoire Libs.
J'ai essayé avec et sans le fichier Tokens.csv mais toujours le même résultat même avec firefox et chrome.
Y a t'il d'autres actions à faire que le simple copie des fichiers ???
Dommage car vraiment ce que je cherche depuis un moment sans succés.

**Comment by Youpit44** [comment]
L'utilisation de page web en local est souvent bloqué par des sécurités sur les nouveaux navigateurs. Par exemple pour Chrome, il faut l'exécuter avec en option : **--allow-file-access-from-files**
Vous pouvez ajouter cette option a la fin de votre raccourci Chrome sur votre bureau.
Un autre problème survient c'est le "cross domain" entre un page local qui appelle une page sur un site web, comme par exemple l'utilisation d'une API. Pour cela je vous conseille de télécharger la base local de Coinmarketcap.com a cette adresse : [cmc.json](https://api.coinmarketcap.com/v1/ticker/?limit=0&convert=EUR) 
et de le sauvegarder sous le nom suivant "cmc.json" dans le dossier contenant la page "index.html"

**Comment by ericnrcoin** [comment]
Ca fonctionne avec ta réponse sur Github mais il ne prend pas le fichier Tokens.csv en compte, faut'il modifier quelque chose dans le code ???
J'ai bien le bon nom qui est dans initScreener.js (tokens.csv)

**Comment by Youpit44** [comment]
Réponse tardive, désolé ! je viens de livrer une toute nouvelle version mieux géré au niveau installation et future mise à jour. Tu trouveras les details sur la page d'accueil.
